title: Talking to Myself
description: some thoughts
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky

permalink: /blog/:year/:month/:day/:title

imagePath: ../../../../assets/images

env: production
indexpage: https://m0op104.github.io/p2/
